### PR TITLE
add pg_stringtheory

### PR DESCRIPTION
**Pull request by wuputah**

### CODE REVIEW

**Review by owenthereal — APPROVED** [review]

**Comment by wuputah** [comment]
@owenthereal it looks like this is trying to build arm64 even though I removed it from the buildkit

**Comment by owenthereal** [comment]
> @owenthereal it looks like this is trying to build arm64 even though I removed it from the buildkit

That's because `arm64` build is [always required](https://github.com/pgxman/buildkit/blob/2ed4f080a53121c9a3f52acb0b1a612e536e70c5/.github/workflows/build.yaml#L39-L43) on CI. We need a dynamic matrix that is based on the buildkit definition.

Is there any plan to support `arm64` for `pg_stringtheory`? Without this, the extension won't work for `arm64` mac

**Comment by wuputah** [comment]
yes, the plan is to fix the issue, this was really a workaround.

**Comment by JerrySievert** [comment]
it was developed on arm64, not sure why it is still failing, though.

**Comment by JerrySievert** [comment]
note that arm64 is macOS, aarch64 is linux.  it should be setting the `HAVE_NEON_INSTRUCTIONS` on both

**Comment by wuputah** [comment]
In pgxman context, I believe "arm64" is really "aarch64". We don't compile on Mac.

**Comment by owenthereal** [comment]
FWIW, `arm64` & `aarch64` refer to the same things. And `arm64` is used more than in the context of macos, e.g. https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images

**Comment by JerrySievert** [comment]
> FWIW, `arm64` & `aarch64` refer to the same thing. And `arm64` is used more than in the context of macos, e.g. https://docs.docker.com/build/building/multi-platform/#building-multi-platform-images

I realize that, but since this uses simd, it's important to include the correct simd code.  therefor, using `uname -s` is important, where macOS returns `arm64` and linux returns `aarch64`, that's the part that matters in this case.  it appears to be a matter of how postgres is using the cppflags based on platform.

**Comment by owenthereal** [comment]
All pgxman builds are performed in a Linux container, it's up to the extension to set any flags necessary for the build process. The `arm64` is used only in the buildkit indicating to docker it should perform a `linux/arm64` run

**Comment by owenthereal** [comment]
I see that https://github.com/hydradatabase/pg_stringtheory/blob/cf4146b482cb4df5298aef644985d54c304aa481/src/sse/common.h#L7 is commented out. Maybe related

**Comment by owenthereal** [comment]
I see that @JerrySievert [made a fix](https://github.com/hydradatabase/pg_stringtheory/commit/cf4146b482cb4df5298aef644985d54c304aa481) that didn't make it to the 1.0.0 reley

**Comment by wuputah** [comment]
I tried that, but that commit didn't fix the build.

**Comment by JerrySievert** [comment]
https://github.com/hydradatabase/pg_stringtheory/commit/1f52833c7ee30c361fe462ab4f56500ee2a08fea

**Pull request merged**
