### PR TITLE
add paradedb pg_bm25

### PR DESCRIPTION
**Pull request by l0vern**

### CODE REVIEW

**Comment by wuputah** [comment]
looks like this one is having trouble building in GHA; the most recent time it looks like it ran out of disk space.

**Comment by l0vern** [comment]
> looks like this one is having trouble building in GHA; the most recent time it looks like it ran out of disk space.

Seems to be doing this on every retry, `arm64` compiled just fine and both compile in local env with no issues. Not sure if theres a way to increase disk space on CI build?

**Comment by owenthereal** [comment]
Restarting the job now it's passing

**Comment by owenthereal** [comment]
CI passing after giving it a more beefy machine.

**Pull request merged**
