### PR TITLE
[HYD-552] Add pg_graphql

### PR DESCRIPTION
**Pull request by owenthereal**
Add pg_graphql

### CODE REVIEW

**Review by wuputah — APPROVED** [review]

**Comment by owenthereal** [comment]
Hmm...the build is failing for pg13:

```console
#35 7.333 ---> Running main build script pg-graphsql (1.4.0)
#35 7.333 Build pg_graphsql
#35 7.413      Creating PGRX_HOME at `/root/.pgrx`
#35 7.424    Validating /usr/lib/postgresql/13/bin/pg_config
#35 7.429    Skipping initdb as current user is root user
#35 13.00        Using PgConfig("pg13") and `pg_config` from /usr/lib/postgresql/13/bin/pg_config
#35 13.00     Building extension with features pg13
#35 13.00      Running command "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "--release" "--features" "pg13" "--no-default-features" "--message-format=json-render-diagnostics"
#35 13.07 error: none of the selected packages contains these features: pg13, did you mean: pg14, pg15, pg16?
```
I reported [here](https://github.com/supabase/pg_graphql/issues/435). Let's disable pg13 for now, considering we are deprecating it anyways.

**Comment by owenthereal** [comment]
Yup, they only support pg14 and above: https://github.com/supabase/pg_graphql/blob/6b9006b2ba81a6a721d3bbf4a00ca7008389bc23/Cargo.toml#L11-L13

**Comment by owenthereal** [comment]
Weird that the build only failed for pg16 on amd64: https://github.com/pgxman/buildkit/actions/runs/6476099335/job/17584271128; pg16 on arm64 was okay. I reported an issue and hope to get some hints: https://github.com/pgcentralfoundation/pgrx/issues/1328.

**Comment by owenthereal** [comment]
The First Rust-based extension is ready 🎉 ! 

I bumped the arm64 worker to the next level because Rust is hungry for CPU when compiling extensions: https://github.com/pgxman/buildkit/pull/26/commits/bba3e6c132d32921586356885ac80b4236e42af6

**Pull request merged**
