### PR TITLE
try to build extensions for pg16

### PR DESCRIPTION
**Pull request by wuputah**
this is an experiment, mostly curious what will happen...

### CODE REVIEW

**Comment by owenthereal** [comment]
Supported pg versions would need to be extended [here](https://github.com/pgxman/pgxman/blob/21fd07cf020df81b457798035e58deaa8ef6cd7e/extension.go#L248-L250). The build image also needs to have pg 16 dev there which is very likely there already.

**Comment by wuputah** [comment]
think it needs a new patch release now?
https://github.com/pgxman/buildkit/blob/main/.github/workflows/build.yaml#L60

**Comment by wuputah** [comment]
so there's some new releases here that will fix the build / add pg16 support, need to track that down, which extensions have new releases and which don't.

atm, we should update:
* pgsql-http
* pg_ivm

haven't investigated yet:
* multicorn
* parquet_s3_fdw

The rest just work.

**Comment by wuputah** [comment]
* parquet_s3_fdw (upstream) hasn't been updated at all since 1.0.0
* multicorn2 updates might have made it pg16 compatible but it's not clear, best to test this offline

**Review by owenthereal — APPROVED** [review]

**Pull request merged**
